/**
 * Asks the installed Better Auth what tables this configuration needs.
 * Used by the generator that writes `schema.sql` and by the test that keeps it
 * honest; never at runtime, where the checked-in file is what runs.
 */
import type { Database } from "bun:sqlite";
import { getMigrations } from "better-auth/db/migration";

import { authOptions } from "./auth.ts";

const HEADER = `-- Generated by scripts/generate-schema.ts from the installed Better Auth and
-- the plugin configuration in src/auth.ts. Do not edit; regenerate.
`;

/**
 * The `user.email` column exactly as Better Auth's migration compiler emits
 * it, and the same column with a case-insensitive collation.
 *
 * SQLite compares text case-sensitively by default, so a user row stored with
 * a capital letter can never be signed in as: Better Auth lowercases the
 * address before it looks the row up and the `=` finds nothing. The login page
 * then reports the same "did not match" it gives a wrong password, which is
 * why #58 survived a whole sitting before anyone saw it. `NOCASE` also makes
 * the column's own unique index case-insensitive, so two personas cannot be
 * seeded as `alice@…` and `Alice@…` either.
 */
const EMAIL_COLUMN = `"email" text not null unique`;
const EMAIL_COLUMN_NOCASE = `${EMAIL_COLUMN} collate nocase`;

/**
 * Better Auth's compiler has no hook for a collation, so the one column is
 * rewritten on the way out rather than hand-edited into `schema.sql` — the
 * file stays generated and `test/schema.test.ts` keeps checking it against the
 * installed library.
 *
 * Throwing rather than returning the SQL unchanged is deliberate. A Better
 * Auth upgrade that renames or re-orders the column would otherwise drop the
 * collation silently, and the next seed would come up green with a persona
 * nobody can log in as — the exact failure #58 is about.
 */
function caseInsensitiveEmail(sql: string): string {
  const table = /create table "user" \([^;]*\)/.exec(sql);
  if (table === null) throw new Error(`no 'create table "user"' statement to patch — Better Auth changed shape`);
  if (!table[0].includes(EMAIL_COLUMN)) {
    throw new Error(`'create table "user"' no longer declares ${EMAIL_COLUMN} — cannot apply collate nocase`);
  }

  return sql.replace(table[0], table[0].replace(EMAIL_COLUMN, EMAIL_COLUMN_NOCASE));
}

export async function compileSchema(db: Database): Promise<string> {
  // The values other than `db` do not shape the schema, so any will do.
  const migrations = await getMigrations(
    authOptions({ db, baseURL: "http://localhost", secret: "schema-generation-only".padEnd(32, "-") }),
  );
  return HEADER + caseInsensitiveEmail(await migrations.compileMigrations());
}
